default_subcategories = {
	'amusement_park': [
		'amusement',
		'rollercoaster',
		'carousel',
		'waterslide',
		'funhouse',
	],
	'art_gallery': ['paintings', 'sculptures', 'exhibitions', 'artists', 'canvas'],
	'bar': ['cocktails', 'bartender', 'beers', 'lounge', 'music'],
	'bowling_alley': ['pins', 'lanes', 'balls', 'shoes', 'strikes'],
	'city_hall': ['mayor', 'council', 'meetings', 'office', 'civic'],
	'hindu_temple': ['deities', 'puja', 'mantras', 'pilgrims', 'rituals'],
	'meal_delivery': ['delivery', 'order', 'courier', 'takeout', 'app'],
	'meal_takeaway': ['fastfood', 'counter', 'takeout', 'service', 'drivethru'],
	'movie_theater': ['cinema', 'screenings', 'popcorn', 'tickets', 'blockbusters'],
	'night_club': ['dj', 'dancefloor', 'party', 'music', 'lights'],
	'point_of_interest': [
		'landmark',
		'attraction',
		'sightseeing',
		'monument',
		'historic',
	],
	'shopping_mall': ['retail', 'stores', 'fashion', 'foodcourt', 'sales'],
	'tourist_attraction': ['landmark', 'sightseeing', 'tour', 'guide', 'visitors'],
	'historical_landmark': ['landmark', 'sightseeing', 'tour', 'guide', 'visitors'],
	'aquarium': ['Sharks', 'Corals', 'Rays', 'Turtles', 'Fishes'],
	'cafe': ['Coffees', 'Pastries', 'Teas', 'Sandwiches', 'Juices'],
	'campground': ['Tents', 'RVs', 'Fires', 'Trails', 'Lakes'],
	'casino': ['Slots', 'Poker', 'Roulette', 'Blackjack', 'Baccarat'],
	'church': ['Choir', 'Organ', 'Altar', 'Nave', 'Steeple'],
	'library': ['Books', 'Journals', 'DVDs', 'Maps', 'Manuscripts'],
	'lodging': ['Hotels', 'Motels', 'Inns', 'Hostels', 'Suites'],
	'mosque': ['Minaret', 'Dome', 'Prayer', 'Mihrab', 'Minbar'],
	'museum': ['Art', 'History', 'Science', 'War', 'Maritime'],
	'park': ['Meadows', 'Forests', 'Lakes', 'Trails', 'Playgrounds'],
	'restaurant': ['Italian', 'Chinese', 'Indian', 'French', 'Mexican'],
	'spa': ['Massages', 'Facials', 'Saunas', 'Pools', 'Yoga'],
	'stadium': ['Football', 'Baseball', 'Soccer', 'Track', 'Concerts'],
	'university': ['Arts', 'Science', 'Law', 'Medicine', 'Engineering'],
	'zoo': ['Mammals', 'Birds', 'Reptiles', 'Amphibians', 'Insects'],
	'performing_arts_theater': ['Drama', 'Comedy', 'Musicals', 'Ballet', 'Opera'],
	'amusement_center': ['Arcade', 'Laser', 'Tag', 'Bumper', 'Cars'],
	'dog_park': ['Dogs', 'Leashes', 'Frisbees', 'Balls', 'Owners'],
	'hiking_area': ['Trails', 'Forests', 'Mountains', 'Rivers', 'Lakes'],
	'national_park': ['Trails', 'Forests', 'Mountains', 'Rivers', 'Lakes'],
	'synagogue': ['Torah', 'Ark', 'Bimah', 'Menorah', 'Kippah'],
	'marina': ['Boats', 'Yachts', 'Sailboats', 'Fishing', 'Docks'],
}
