categories_keywords_single = {
    "dining": {
        "american_restaurant": ["burgers", "steaks", "fries", "cuisine"],
        "bakery": ["bread", "pastries", "cakes", "sandwiches"],
        "bar": ["cocktails", "beer", "wine", "spirits"],
        "barbecue_restaurant": ["ribs", "brisket", "smoked", "BBQ"],
        "brazilian_restaurant": ["churrasco", "feijoada", "caipirinha", "rodizio"],
        "breakfast_restaurant": ["pancakes", "eggs", "omelettes", "coffee"],
        "brunch_restaurant": ["mimosas", "avocado", "eggs", "pastries"],
        "cafe": ["coffee", "tea", "pastries", "sandwiches"],
        "chinese_restaurant": ["dumplings", "stir-fry", "wonton", "duck"],
        "fast_food_restaurant": ["burgers", "nuggets", "fries", "shakes"],
        "french_restaurant": ["escargot", "vin", "baguettes", "croissants"],
        "greek_restaurant": ["gyros", "moussaka", "salad", "baklava"],
        "hamburger_restaurant": ["burgers", "cheeseburgers", "milkshakes", "fries"],
        "ice_cream_shop": ["ice", "gelato", "sundaes", "cones"],
        "indian_restaurant": ["curry", "naan", "biryani", "samosas"],
        "indonesian_restaurant": ["nasi", "satay", "rendang", "sambal"],
        "italian_restaurant": ["pizza", "pasta", "gelato", "espresso"],
        "japanese_restaurant": ["sushi", "ramen", "tempura", "sake"],
        "korean_restaurant": ["kimchi", "bibimbap", "bulgogi", "BBQ"],
        "lebanese_restaurant": ["hummus", "tabbouleh", "falafel", "shawarma"],
        "meal_delivery": ["delivery", "ordering", "home", "kits"],
        "meal_takeaway": ["takeout", "fast", "orders", "pickup"],
        "mediterranean_restaurant": ["falafel", "hummus", "gyro", "tabbouleh"],
        "mexican_restaurant": ["tacos", "burritos", "enchiladas", "margaritas"],
        "middle_eastern_restaurant": ["kebabs", "falafel", "hummus", "baklava"],
        "pizza_restaurant": ["pizza", "calzones", "knots", "sticks"],
        "ramen_restaurant": ["ramen", "noodle", "gyoza", "bao"],
        "restaurant": ["dining", "cuisine", "meals", "service"],
        "sandwich_shop": ["sandwiches", "subs", "paninis", "wraps"],
        "seafood_restaurant": ["lobster", "crab", "shrimp", "fish"],
        "spanish_restaurant": ["tapas", "paella", "sangria", "churros"],
        "steak_house": ["steaks", "ribs", "filet", "sirloin"],
        "sushi_restaurant": ["sushi", "sashimi", "nigiri", "maki"],
        "thai_restaurant": ["pad", "curry", "rolls", "soup"],
        "turkish_restaurant": ["kebabs", "baklava", "meze", "delight"],
        "vegan_restaurant": ["plant-based", "burgers", "salads", "tofu"],
        "vegetarian_restaurant": ["vegetarian", "options", "salads", "dishes"],
        "vietnamese_restaurant": ["pho", "banh", "rolls", "coffee"],
    },
    "default_categories": {
        "tourist_attraction": ["landmarks", "sightseeing", "tours", "destinations"],
        "historical_landmark": ["monuments", "sites", "heritage", "tours"],
        "museum": ["exhibitions", "art", "history", "artifacts"],
    },
    "categories_nlp": {
        "art_gallery": ["paintings", "exhibitions", "art", "sculptures"],
        "performing_arts_theater": ["plays", "musicals", "performances", "opera"],
        "amusement_center": ["arcade", "laser", "activities", "entertainment"],
        "amusement_park": ["coasters", "rides", "themed", "parks"],
        "aquarium": ["marine", "exhibits", "fish", "tours"],
        "bowling_alley": ["bowling", "league", "arcade", "fun"],
        "casino": ["gambling", "slots", "poker", "entertainment"],
        "church": ["worship", "services", "events", "gatherings"],
        "hindu_temple": ["puja", "festivals", "rituals", "events"],
        "mosque": ["prayer", "gatherings", "services", "celebrations"],
        "synagogue": ["services", "readings", "events", "Mitzvahs"],
        "dog_park": ["off-leash", "friendly", "exercise", "socialization"],
        "hiking_area": ["trails", "walks", "adventure", "views"],
        "city_hall": ["services", "management", "meetings", "events"],
        "library": ["books", "reading", "resources", "programs"],
        "marina": ["boating", "dockage", "activities", "sailing"],
        "movie_theater": ["films", "cinema", "popcorn", "nights"],
        "night_club": ["dancing", "music", "drinks", "nightlife"],
        "national_park": ["beauty", "conservation", "camping", "hiking"],
        "park": ["spaces", "playgrounds", "picnics", "activities"],
        "restaurant": ["dining", "cuisine", "meals", "service"],
        "spa": ["relaxation", "massages", "treatments", "services"],
        "stadium": ["sports", "concerts", "gatherings", "competitions"],
        "university": ["education", "campuses", "research", "life"],
        "zoo": ["animals", "conservation", "programs", "outings"],
    }
}
